services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    networks:
      - my-network

  inventory-service:
    build: ./inventory-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    networks:
      - my-network

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    networks:
      - my-network

  api-gateway:
    build: ./api-gateway  # Путь к директории с вашим API Gateway
    ports:
      - "8080:8080"
    depends_on:
      - inventory-service
      - order-service
    networks:
      - my-network

volumes:
  mongo_data:

networks:
  my-network:
    driver: bridge
